aspnetmvc/BurgerWebApp/BurgerWebApp/Controllers/BurgerController.cs
using Microsoft.AspNetCore.Mvc;
using Business.Abstraction;
using ViewModels;

namespace BurgerWebApp.Controllers
{
    public class BurgerController : Controller
    {
        private readonly IBurgerService _burgerService;

        public BurgerController(IBurgerService burgerService)
        {
            _burgerService = burgerService;
        }

        public IActionResult Index()
        {
            return View(_burgerService.GetAll());
        }

        public IActionResult Details(int id)
        {
            var burger = _burgerService.GetById(id);
            return View(burger);
        }

        public IActionResult CreateEditBurger(int? id)
        {
            var model = id.HasValue ? _burgerService.GetById(id.Value) : new BurgerViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Save(BurgerViewModel model)
        {
            _burgerService.Save(model);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _burgerService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

aspnetmvc/BurgerWebApp/BurgerWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Business.Abstraction;
using ViewModels;

namespace BurgerWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMenuService _menuService;

        public HomeController(ILogger<HomeController> logger, IMenuService menuService)
        {
            _logger = logger;
            _menuService = menuService;
        }

        public IActionResult Index()
        {
            return View(_menuService.GetAll());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

aspnetmvc/BurgerWebApp/BurgerWebApp/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using Business.Abstraction;
using ViewModels;

namespace BurgerWebApp.Controllers
{
    public class MenuController : Controller
    {
        private readonly IMenuService _menuService;
        private readonly IBurgerService _burgerService;
        private readonly ISizeService _SizeService;

        public MenuController(IMenuService menuService, IBurgerService burgerService, ISizeService sizeService)
        {
            _menuService = menuService;
            _burgerService = burgerService;
            _SizeService = sizeService;
        }

        public IActionResult Index()
        {
            return View(_menuService.GetAll());
        }

        public IActionResult CreateEditMenuItem(int? id)
        {
            var menuItem = id.HasValue ? _menuService.GetById(id.Value) : new MenuItemViewModel();

            ViewBag.Burgers = _burgerService.GetBurgersSelectList();
            ViewBag.Sizes =  _SizeService.GetSizesSelectList();

            return View(menuItem);
        }

        public IActionResult Save(MenuItemViewModel model)
        {
            _menuService.Save(model);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _menuService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

aspnetmvc/BurgerWebApp/BurgerWebApp/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using ViewModels;
using Business.Abstraction;

namespace BurgerWebApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        public IActionResult Index()
        {
            return View(_orderService.GetAll());
        }

        public IActionResult CreateOrder()
        {
            return View(new OrderViewModel());
        }

        [HttpPost]
        public IActionResult Save(OrderViewModel model)
        {
            var id = _orderService.Save(model);

            return RedirectToAction("Details", new { id = id });
        }

        public IActionResult Details(int id)
        {
            return View(_orderService.Details(id));
        }

        public IActionResult Delete(int id)
        {
            _orderService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

aspnetmvc/BurgerWebApp/BurgerWebApp/Controllers/OrderItemController.cs
using Microsoft.AspNetCore.Mvc;
using ViewModels;
using Business.Abstraction;

namespace BurgerWebApp.Controllers
{
    public class OrderItemController : Controller
    {
        private readonly IOrderItemService _orderItemService;
        private readonly IMenuService _menuService;

        public OrderItemController(IOrderItemService orderItemService, IMenuService menuService)
        {
            _orderItemService = orderItemService;
            _menuService = menuService;
        }

        public IActionResult CreateOrderItem(int id)
        {
            ViewBag.MenuItems = _menuService.GetMenuItemsSelectList();

            var orderItem = new OrderItemViewModel()
            {
                OrderId = id
            };

            return View(orderItem);
        }

        [HttpPost]
        public IActionResult Save(OrderItemViewModel model)
        {
             _orderItemService.Save(model);
            return RedirectToAction("Details", "Order", new { id = model.OrderId });
        }

        public IActionResult Delete(int id)
        {
            var orderId = _orderItemService.Delete(id);

            return RedirectToAction("Details", "Order", new { id = orderId });
        }
    }
}

aspnetmvc/BurgerWebApp/BurgerWebApp/Controllers/SizeController.cs
using Microsoft.AspNetCore.Mvc;
using ViewModels;
using Business.Abstraction;

namespace BurgerWebApp.Controllers
{
    public class SizeController : Controller
    {
        private readonly ISizeService _sizeService;

        public SizeController(ISizeService sizeService)
        {
            _sizeService = sizeService;
        }

        public IActionResult Index()
        {
            return View(_sizeService.GetAll());
        }

        public IActionResult CreateEditSize(int? id)
        {
            var model = id.HasValue ? _sizeService.Details(id.Value) : new SizeViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Save(SizeViewModel model)
        {
            _sizeService.Save(model);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _sizeService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

aspnetmvc/BurgerWebApp/BurgerWebApp/Views/Burger/CreateEditBurger.cshtml
@model BurgerViewModel

<form method="post" asp-action="Save" asp-controller="Burger">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
    </div>
    <div class="form-group mb-3">
        <label asp-for="ImageUrl"></label>
        <input asp-for="ImageUrl" class="form-control" />
    </div>
    <input type="submit" class="btn btn-primary float-right" value="Save" />
</form>

aspnetmvc/BurgerWebApp/BurgerWebApp/Views/Burger/Details.cshtml
@model BurgerViewModel

<div class="d-flex justify-content-center">
    <div>
        <h3 class="mb-3">@Model.Name</h3>
        <img src="@Model.ImageUrl" alt="@Model.Name" class="rounded float-left col-4 mb-3" style="width: 600px; height: 600px;" />
        <span class="col-6">
            <h6>Ingredients: @Model.Description</h6>
        </span>
    </div>
</div>

aspnetmvc/BurgerWebApp/BurgerWebApp/Views/Burger/Index.cshtml
@model List<BurgerViewModel>

<a asp-action="CreateEditBurger" class="btn btn-primary mb-3">Add new</a>
<div class="border rounded shadow">
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 0; i < Model.Count; i++)
            {
                <tr>
                    <th scope="row">@(i + 1)</th>
                    <td>@Model[i].Name</td>
                    <td>@Model[i].Description</td>
                    <td>
                        <a asp-action="Details" asp-route-id="@Model[i].Id" class="btn btn-primary">Details</a>
                        <a asp-action="CreateEditBurger" asp-controller="Burger" asp-route-id="@Model[i].Id" class="btn btn-warning">Edit</a>
                        <a asp-action="Delete" asp-controller="Burger" asp-route-id="@Model[i].Id" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

aspnetmvc/BurgerWebApp/BurgerWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center pb-5">
    <h1 class="display-4">Welcome To The Bite Me! Burger</h1>
</div>

<div class="container">
    <div class="text-center pb-3">
        <h2>Top irresistable bites!!!</h2>
    </div>
    <div class="row justify-content-evenly">
        <div class="card col-4 p-0" style="width: 18rem;">
            <img src="@Url.Content(Model[0].Burger.ImageUrl)" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Cheeseburger</h5>
                <p class="card-text">@Model[0].Burger.Description</p>
            </div>
            @*            <div class="card-body d-flex justify-content-center">
            <a href="#" class="card-link">Make order</a>
            </div>*@
        </div>
        <div class="card col-4 p-0" style="width: 18rem;">
            <img src="@Url.Content(Model[6].Burger.ImageUrl)" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Hamburger</h5>
                <p class="card-text">@Model[6].Burger.Description</p>
            </div>
            @*            <div class="card-body d-flex justify-content-center">
            <a href="#" class="card-link">Make order</a>
            </div>*@
        </div>
        <div class="card col-4 p-0" style="width: 18rem;">
            <img src="@Url.Content(Model[3].Burger.ImageUrl)" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Crispy Chickenburger</h5>
                <p class="card-text">@Model[3].Burger.Description</p>
            </div>
            @*            <div class="card-body d-flex justify-content-center">
            <a href="#" class="card-link">Make order</a>
            </div>*@
        </div>
    </div>
</div>

aspnetmvc/BurgerWebApp/BurgerWebApp/Views/Menu/CreateEditMenuItem.cshtml
@model MenuItemViewModel

<form method="post" asp-action="Save" asp-controller="Menu">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="BurgerId"></label>
        <select asp-for="BurgerId" asp-items="@(IEnumerable<SelectListItem>) ViewBag.Burgers" class="form-control">
            <option>-- Select burger --</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="SizeId"></label>
        <select asp-for="SizeId" asp-items="@(IEnumerable<SelectListItem>) ViewBag.Sizes" class="form-control">
            <option>-- Select size --</option>
        </select>
    </div>
    <div class="form-group mb-3">
        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control" />
    </div>
    <input type="submit" class="btn btn-primary float-right" value="Save" />
</form>

aspnetmvc/BurgerWebApp/BurgerWebApp/Views/Menu/Index.cshtml
@model List<MenuItemViewModel>

<a asp-action="CreateEditMenuItem" class="btn btn-primary mb-3">Add new</a>
<div class="border rounded shadow">
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Size</th>
                <th scope="col">Price</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 0; i < Model.Count; i++)
            {
                <tr>
                    <th scope="row">@(i + 1)</th>
                    <td>@Model[i].Burger.Name (@Model[i].Burger.Description)</td>
                    <td>@Model[i].Size.Name (@Model[i].Size.Description)</td>
                    <td>@Model[i].Price</td>
                    <td>
                        <a asp-action="CreateEditMenuItem" class="btn btn-warning" asp-route-id="@Model[i].Id">Edit</a>
                        <a asp-action="Delete" class="btn btn-danger" asp-route-id="@Model[i].Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

aspnetmvc/BurgerWebApp/BurgerWebApp/Views/Order/CreateOrder.cshtml
@model OrderViewModel

<form method="post" asp-action="Save" asp-controller="Order">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber"></label>
        <input asp-for="PhoneNumber" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
    </div>
    <div class="form-group mb-3">
        <label asp-for="Note"></label>
        <input asp-for="Note" class="form-control" />
    </div>
    <input type="submit" class="btn btn-primary float-right" value="Save" />
</form>

aspnetmvc/BurgerWebApp/BurgerWebApp/Views/Order/Details.cshtml
@using System.Globalization;
@model OrderViewModel

<div class="container">
    <div class="mb-3">
        <p class="fs-3">Name <span>@Model.Name</span></p>
        <p class="fs-3">Address: <span>@Model.Address</span></p>
        <p class="fs-3">Phone Number: <span>@Model.PhoneNumber</span></p>
        <p class="fs-3">Note: <span>@Model.Note</span></p>
        <p class="fs-3">Total: <span>@Model.TotalPrice.ToString("C", CultureInfo.CreateSpecificCulture("mk-MK"))</span></p>
    </div>

    <a asp-action="CreateOrderItem" asp-controller="OrderItem" asp-route-id="@Model.Id" class="btn btn-primary mb-3">Add Item</a>

    <div class="border rounded shadow">
        <table class="table">
            <thead class="table-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Pizza</th>
                    <th scope="col">Quantity</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @for (var i = 0; i < Model.Items.Count; i++)
                {
                    <tr>
                        <th scope="row">@(i + 1)</th>
                        <td>@Model.Items[i].MenuItem.ToString()</td>
                        <td>@Model.Items[i].Quantity</td>
                        <td>
                            <a asp-action="Delete" asp-controller="OrderItem" asp-route-id="@Model.Items[i].Id" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

aspnetmvc/BurgerWebApp/BurgerWebApp/Views/Order/Index.cshtml
@model List<OrderViewModel>

<a asp-action="CreateOrder" class="btn btn-primary mb-3">Add new</a>
<div class="border rounded shadow">
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Phone number</th>
                <th scope="col">Address</th>
                <th scope="col">Note</th>
                <th scope="col">Total price</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 0; i < Model.Count; i++)
            {
                <tr>
                    <th scope="row">@(i + 1)</th>
                    <td>@Model[i].Name</td>
                    <td>@Model[i].PhoneNumber</td>
                    <td>@Model[i].Address</td>
                    <td>@Model[i].Note</td>
                    <td>@Model[i].TotalPrice</td>
                    <td>
                        <a asp-action="Details" asp-controller="Order" asp-route-id="@Model[i].Id" class="btn btn-warning">Details</a>
                        <a asp-action="Delete" asp-controller="Order" asp-route-id="@Model[i].Id" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

aspnetmvc/BurgerWebApp/BurgerWebApp/Views/OrderItem/CreateOrderItem.cshtml
@model OrderItemViewModel

<form method="post" asp-action="Save">
    <input type="hidden" asp-for="OrderId"/>
    <div class="form-group">
        <label asp-for="MenuItem.Id"></label>
        <select asp-for="MenuItem.Id" asp-items="@(IEnumerable<SelectListItem>) ViewBag.MenuItems" class="form-control">
            <option>-- Please select burger --</option>
        </select>
    </div>
    <div class="form-group mb-3">
        <label asp-for="Quantity"></label>
        <input asp-for="Quantity" class="form-control" />
    </div>
    <input type="submit" class="btn btn-primary float-right" value="Save" />
</form>

aspnetmvc/BurgerWebApp/BurgerWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BurgerWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BurgerWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://i.pinimg.com/736x/a2/f5/a3/a2f5a32f863b0f31fcb5561a8f032bfc.jpg" alt="" width="30" height="30" class="d-inline-block align-text-top">
                    Bite Me! Burger
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Menu" asp-action="Index">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Burger" asp-action="Index">Burgers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Size" asp-action="Index">Sizes</a>
                        </li>
                         <li>  <a class="nav-link text-white" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BurgerWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

aspnetmvc/BurgerWebApp/BurgerWebApp/Views/Size/CreateEditSize.cshtml
@model SizeViewModel

<form method="post" asp-action="Save" asp-controller="Size">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group mb-3">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
    </div>
    <input type="submit" class="btn btn-primary float-right" value="Save" />
</form>

aspnetmvc/BurgerWebApp/BurgerWebApp/Views/Size/Index.cshtml
@model List<SizeViewModel>

<a asp-action="CreateEditSize" class="btn btn-primary mb-3">Add new</a>
<div class="border rounded shadow">
    <table class="table">
        <thead class="table-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 0; i < Model.Count; i++)
            {
                <tr>
                    <th scope="row">@(i + 1)</th>
                    <td>@Model[i].Name</td>
                    <td>@Model[i].Description</td>
                    <td>
                        <a asp-action="CreateEditSize" asp-controller="Size" asp-route-id="@Model[i].Id" class="btn btn-warning">Edit</a>
                        <a asp-action="Delete" asp-controller="Size" asp-route-id="@Model[i].Id" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>